# Generated by Django 4.2.7 on 2023-11-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('brand', models.CharField(default='Desc', max_length=100)),
                ('rating', models.IntegerField(default='100')),
                ('carName', models.CharField(default='Desc', max_length=100)),
                ('year', models.IntegerField(default='2001')),
                ('imgUrl', models.ImageField(default='Desc', upload_to=None)),
                ('model', models.CharField(default='Desc', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('speed', models.IntegerField(default='70')),
                ('gps', models.CharField(default='gps 2.0', max_length=100)),
                ('transmission', models.CharField(default='Desc', max_length=100)),
                ('description', models.CharField(default='Desc', max_length=200)),
            ],
        ),
    ]
