# Generated by Django 4.2.7 on 2023-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imgUrl',
            field=models.ImageField(upload_to='car_images'),
        ),
    ]
